import {
  FlaskConical,
  Waves,
  Compass,
  Telescope,
  Route,
  Sparkles,
  BookOpenText,
  Map,
  Radio,
  Users,
  TrendingUp,
  CircleUser,
  LayoutDashboard,
  GraduationCap,
  Library,
  ClipboardCheck,
  BarChart3,
  Settings,
  Milestone,
  Wrench,
  ShoppingBag,
  CreditCard,
  Gift,
  AudioLines,
  CalendarDays,
  HeartPulse,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/config/navigation";

/** Resuelve la clave de ícono (string serializable, del lado servidor) al
 *  componente Lucide. Compartido por AppSidebar y BottomNav. */
export const ICONS: Record<IconName, LucideIcon> = {
  waves: Waves,
  compass: Compass,
  explore: Telescope,
  route: Route,
  sparkles: Sparkles,
  book: BookOpenText,
  map: Map,
  radio: Radio,
  audio: AudioLines,
  calendar: CalendarDays,
  users: Users,
  trending: TrendingUp,
  user: CircleUser,
  dashboard: LayoutDashboard,
  students: GraduationCap,
  academia: GraduationCap,
  roadmap: Milestone,
  tools: Wrench,
  store: ShoppingBag,
  membership: CreditCard,
  gift: Gift,
  library: Library,
  clipboard: ClipboardCheck,
  chart: BarChart3,
  settings: Settings,
  heart: HeartPulse,
  flask: FlaskConical,
};
