-- ============================================================
-- OCEOM by E-MOTION® — Semilla inicial de la red BIOCODE.
--
-- Arranque de la base de conocimiento con los casos que el documento de
-- Valeria usa como ejemplo. Cada nodo declara su nivel de evidencia y separa
-- lo educativo de lo complementario; la mentora amplía la red desde el panel.
--
-- Idempotente: `on conflict (slug) do nothing` para poder re-correrla.
-- ============================================================

insert into biocode_nodes (
  slug, name, category, body_zone, organ, body_system,
  scientific_info, scientific_sources, warning_signs,
  complementary_info, symbolic_themes,
  emotions, beliefs, patterns, behaviors, questions, exercises,
  related_slugs, oceom_resource, oceom_link, evidence_level
) values

-- ── Síntomas ──
('migrana', 'Migraña', 'sintoma', 'cabeza', 'cerebro', 'nervioso',
 'La migraña es un trastorno neurológico, no un simple dolor de cabeza. Cursa con dolor pulsátil que suele afectar un lado, y puede acompañarse de náuseas y de sensibilidad a la luz y al sonido. Entre los desencadenantes descritos con más frecuencia están el estrés, los cambios de sueño, el ayuno prolongado, cambios hormonales y ciertos alimentos. Tiene tratamientos eficaces: vale la pena consultar.',
 '{"Organización Mundial de la Salud — trastornos por cefalea","International Classification of Headache Disorders (ICHD-3)"}',
 '{"El peor dolor de cabeza de tu vida, de aparición súbita","Dolor de cabeza con fiebre y rigidez de cuello","Dolor acompañado de confusión, dificultad para hablar o pérdida de fuerza","Dolor tras un golpe en la cabeza","Cambio brusco en el patrón habitual de tus dolores de cabeza"}',
 'En algunos enfoques complementarios se explora la migraña en relación con la autoexigencia sostenida y con la dificultad para soltar el control. No hay evidencia de que una emoción cause migraña; se usa únicamente como puerta de reflexión sobre el ritmo de vida.',
 '{"autoexigencia","presión sostenida","necesidad de control","dificultad para descansar","conflicto interno"}',
 '{"presión","frustración","ansiedad","impotencia"}',
 '{"Tengo que poder con todo","No puedo equivocarme","Si descanso, estoy perdiendo el tiempo","Todo depende de mí"}',
 '{"sobrecontrol","perfeccionismo","postergar el descanso"}',
 '{"sobretrabajar","controlar","postergar"}',
 '{"¿Cuándo comenzó?","¿Qué estaba ocurriendo en tu vida en ese momento?","¿Qué situación estaba generando presión?","¿Qué estabas intentando controlar?","¿Te permites descansar sin sentir culpa?","¿Qué ocurre emocionalmente antes de que aparezca?"}',
 '{"Respiración de regulación antes de que el día te alcance","Registro de autoobservación: qué ocurrió las 24 horas previas","Escritura: qué estoy sosteniendo que no me toca sostener"}',
 '{"sobreexigencia","cuello-hombros"}',
 'Prácticas de respiración y regulación', '/lab/respiracion', 'complementario'),

('dolor-espalda', 'Dolor de espalda', 'sintoma', 'espalda', 'columna', 'musculoesquelético',
 'El dolor de espalda es uno de los motivos de consulta más frecuentes del mundo. En la mayoría de los casos es inespecífico y mejora con movimiento, actividad gradual y manejo del estrés; el reposo prolongado suele empeorarlo. El estrés sostenido aumenta la tensión muscular, lo que puede intensificar la percepción del dolor.',
 '{"Organización Mundial de la Salud — lumbalgia","The Lancet Low Back Pain Series"}',
 '{"Dolor tras un traumatismo importante","Pérdida de fuerza, hormigueo o adormecimiento en las piernas","Pérdida de control de esfínteres","Fiebre acompañando al dolor","Pérdida de peso sin explicación"}',
 'Desde una perspectiva simbólica, algunas corrientes complementarias exploran la espalda en relación con las cargas que se sostienen y con el sentirse sin apoyo. Es una lectura de reflexión, no una explicación del dolor.',
 '{"cargas que sostengo","falta de sostén","sensación de estar sola en el peso"}',
 '{"agotamiento","impotencia","resentimiento silencioso"}',
 '{"Si yo no lo hago, no lo hace nadie","Pedir ayuda es una debilidad","Tengo que ser el soporte de todos"}',
 '{"sobrecarga","dificultad para delegar","cuidar a todos"}',
 '{"sobretrabajar","complacer","aguantar"}',
 '{"¿Qué estás sosteniendo en este momento de tu vida?","¿Qué de eso no te corresponde?","¿A quién podrías pedirle ayuda y no se la has pedido?","¿Qué pasaría si soltaras una sola de esas cargas?"}',
 '{"Escritura: lista de todo lo que sostengo y qué es realmente mío","Movimiento suave diario","Un pedido concreto de ayuda esta semana"}',
 '{"merecimiento","sobreexigencia"}',
 'Sanación del merecimiento — E-MOTION', null, 'complementario'),

('digestivo-estomago', 'Estómago y digestión', 'sintoma', 'abdomen', 'estómago', 'digestivo',
 'El aparato digestivo y el sistema nervioso están estrechamente conectados: el estrés puede modificar la motilidad intestinal y la percepción de molestias. Esto sí tiene respaldo científico y explica por qué los periodos de tensión suelen sentirse en el estómago. No significa que toda molestia digestiva sea emocional: los síntomas persistentes deben valorarse médicamente.',
 '{"Investigación sobre el eje intestino-cerebro","Guías clínicas de trastornos funcionales digestivos"}',
 '{"Vómito con sangre o heces negras","Pérdida de peso sin explicación","Dificultad para tragar","Dolor abdominal intenso y persistente","Síntomas que despiertan por la noche"}',
 'En enfoques complementarios se explora la digestión en relación con lo que cuesta asimilar o aceptar de una situación. Es material de reflexión, no una causa.',
 '{"lo que no logro digerir","dificultad para asimilar un cambio","tragarse las palabras"}',
 '{"ansiedad","preocupación anticipatoria","rabia contenida"}',
 '{"No puedo decir lo que pienso","Tengo que aguantarme"}',
 '{"anticipación","rumiación"}',
 '{"evitar","aislarse","postergar conversaciones"}',
 '{"¿Qué situación te está costando digerir?","¿Hay algo que no has podido decir?","¿Qué se te revuelve cuando piensas en eso?"}',
 '{"Respiración diafragmática antes de comer","Journaling: qué necesito decir y a quién"}',
 '{"culpa"}',
 'Journaling terapéutico', '/bitacora', 'investigacion'),

('cuello-hombros', 'Cuello y hombros', 'cuerpo', 'cuello', null, 'musculoesquelético',
 'La tensión en cuello y hombros es muy frecuente y suele relacionarse con posturas sostenidas, trabajo frente a pantallas y estrés. El movimiento regular y las pausas activas son de lo más eficaz que existe para aliviarla.',
 '{"Guías de salud musculoesquelética ocupacional"}',
 '{"Dolor de cuello tras un accidente","Rigidez de cuello con fiebre","Pérdida de fuerza o sensibilidad en brazos o manos"}',
 'Algunas corrientes complementarias exploran esta zona en relación con la rigidez ante los cambios y con el peso de la responsabilidad. Es una lectura simbólica.',
 '{"rigidez ante el cambio","peso de la responsabilidad","estar en guardia"}',
 '{"tensión","alerta permanente","exigencia"}',
 '{"No me puedo relajar","Si bajo la guardia, algo malo pasa"}',
 '{"hipervigilancia","sobrecontrol"}',
 '{"controlar","sobretrabajar"}',
 '{"¿En qué parte de tu vida estás en guardia?","¿Qué responsabilidad estás cargando sin haberla elegido?"}',
 '{"Pausas activas cada hora","Respiración larga con exhalación extendida"}',
 '{"migrana","sobreexigencia"}',
 'Prácticas de respiración', '/lab/respiracion', 'complementario'),

('insomnio', 'Dificultad para dormir', 'sintoma', 'cabeza', null, 'nervioso',
 'El insomnio tiene tratamiento y el más eficaz según la evidencia es la terapia cognitivo-conductual para el insomnio, por encima de la medicación a largo plazo. Cuidar los horarios, la exposición a luz y el uso de pantallas antes de dormir tiene impacto real.',
 '{"Guías clínicas sobre insomnio — terapia cognitivo-conductual (TCC-I)"}',
 '{"Somnolencia diurna intensa que afecta tu seguridad","Ronquidos con pausas respiratorias","Insomnio junto con ánimo muy bajo sostenido"}',
 'Desde una lectura simbólica se explora la dificultad para dormir en relación con soltar el control y con la sensación de que algo queda sin resolver.',
 '{"dificultad para soltar","algo sin cerrar","hipervigilancia"}',
 '{"ansiedad","preocupación","miedo"}',
 '{"Si me duermo, pierdo el control","Tengo que resolverlo todo hoy"}',
 '{"rumiación nocturna","sobrecontrol"}',
 '{"controlar","postergar el descanso"}',
 '{"¿Qué es lo primero que aparece en tu mente cuando apagas la luz?","¿Qué quedó sin cerrar hoy?"}',
 '{"Escritura de descarga antes de dormir","Respiración 4-7-8","Meditación guiada de Deep Waves"}',
 '{"sobreexigencia"}',
 'Deep Waves — meditación para dormir', '/deep-waves', 'consolidada'),

-- ── Emociones ──
('abandono', 'Abandono', 'emocion', null, null, null,
 null, '{}', '{}',
 'El miedo al abandono suele explorarse en relación con experiencias tempranas de vínculo. En psicología del apego esto sí tiene desarrollo teórico y clínico; como exploración personal, sirve para entender patrones actuales de vínculo sin buscar culpables.',
 '{"miedo a ser dejada","necesidad de asegurar el vínculo","hipervigilancia afectiva"}',
 '{"miedo","tristeza","angustia","inseguridad"}',
 '{"Me van a dejar","No soy suficiente","Tengo que hacer algo para que se queden","Si me muestro como soy, se van"}',
 '{"patrones repetitivos de pareja","elegir personas emocionalmente indisponibles"}',
 '{"dependencia","hipervigilancia","necesidad de aprobación","dificultad para poner límites"}',
 '{"¿Cuándo sentiste esto por primera vez?","¿Qué haces cuando temes que alguien se aleje?","¿Qué necesitas para sentirte segura contigo misma?","¿Qué te dices cuando alguien tarda en responderte?"}',
 '{"Reconstrucción de seguridad interna","Escritura: carta a la niña que sintió eso por primera vez","Un límite pequeño esta semana"}',
 '{"merecimiento","culpa"}',
 'Sanación de la niñez — E-MOTION', null, 'investigacion'),

('culpa', 'Culpa', 'emocion', null, null, null,
 null, '{}', '{}',
 'La culpa sostenida suele explorarse como una señal de que estás midiendo tu valor por lo que haces por otros. Distinguir entre culpa útil (reparar algo concreto) y culpa crónica (sentirte en falta permanente) abre camino.',
 '{"medir el valor por lo que doy","sentirme en falta permanente","responsabilidad desmedida"}',
 '{"culpa","vergüenza","tristeza"}',
 '{"Si me pongo primero, soy egoísta","Tengo que sacrificarme","Si digo que no, dejarán de quererme"}',
 '{"complacer","autoexigencia","cuidar a todos"}',
 '{"complacer","postergarse","pedir perdón de más"}',
 '{"¿De qué te sientes culpable exactamente?","¿Hay algo concreto que puedas reparar, o es una culpa que te acompaña siempre?","¿Qué te enseñaron sobre poner tus necesidades primero?","¿Qué pasaría si dijeras que no una vez esta semana?"}',
 '{"Ejercicio de límites: un no amable esta semana","Escritura: qué es mío y qué no lo es"}',
 '{"merecimiento","abandono"}',
 'Módulo de merecimiento — E-MOTION', null, 'complementario'),

-- ── Creencias y patrones ──
('merecimiento', 'Merecimiento', 'creencia', null, null, null,
 null, '{}', '{}',
 'El merecimiento se explora como la relación con recibir: dinero, amor, reconocimiento, descanso, placer, éxito, bienestar. La distinción clave es entre sacrificio (debo sufrir para merecer) y propósito (puedo construir desde el sentido, el valor y el disfrute).',
 '{"dificultad para recibir","asociar esfuerzo con merecimiento","culpa al descansar"}',
 '{"culpa","vergüenza","inseguridad"}',
 '{"No merezco recibir","Debo demostrar mi valor","Tengo que sacrificarme","Primero los demás"}',
 '{"cuando empiezo a ganar más aparece una crisis","me cuesta recibir","termino agotada demostrando mi valor"}',
 '{"rechazar ayuda","autosabotearse","sobretrabajar"}',
 '{"¿Qué sientes cuando recibes sin haber sufrido primero?","¿Te permites recibir ayuda?","¿Sientes culpa cuando descansas?","¿Necesitas demostrar tu valor para sentirte en paz?"}',
 '{"Recibir un cumplido sin devolverlo ni minimizarlo","Pedir una ayuda concreta esta semana","Escritura: qué me enseñaron sobre merecer"}',
 '{"culpa","abandono","dinero"}',
 'Módulo de merecimiento — E-MOTION', null, 'complementario'),

('sobreexigencia', 'Sobreexigencia', 'patron', null, null, null,
 null, '{}', '{}',
 'La sobreexigencia se explora como un patrón de respuesta aprendido: exigirse funcionó alguna vez para sentirse segura o valorada, y luego se volvió automático. La neuroplasticidad explica que lo repetido se automatiza, y también que se pueden construir respuestas nuevas.',
 '{"exigirse para sentirse valiosa","el descanso como amenaza","perfeccionismo"}',
 '{"presión","ansiedad","frustración","agotamiento"}',
 '{"Tengo que poder con todo","No puedo equivocarme","Descansar es perder el tiempo","Si no es perfecto, no sirve"}',
 '{"perfeccionismo","dificultad para delegar","agotamiento recurrente"}',
 '{"sobretrabajar","controlar","postergar el descanso"}',
 '{"¿Qué crees que pasaría si lo hicieras al 80 por ciento?","¿De quién aprendiste que había que exigirse así?","¿Qué te dices cuando descansas?"}',
 '{"Entregar algo al 80 por ciento a propósito","Bloquear un descanso en la agenda y respetarlo","Delegar una sola tarea esta semana"}',
 '{"migrana","cuello-hombros","merecimiento"}',
 'Prácticas de regulación', '/lab/respiracion', 'complementario'),

('dinero', 'Relación con el dinero', 'patron', null, null, null,
 null, '{}', '{}',
 'La relación con el dinero se explora en vínculo con la seguridad, el merecimiento y los patrones familiares alrededor de lo económico. No es asesoría financiera: es mirar las creencias que operan cuando se trata de recibir y sostener.',
 '{"seguridad","merecimiento","lealtades familiares con lo económico"}',
 '{"miedo","culpa","ansiedad"}',
 '{"El dinero es difícil","No merezco recibir","En mi familia siempre ha sido así","Si tengo, alguien pierde"}',
 '{"cuando empiezo a ganar más aparece una crisis","gastar lo que llega","no cobrar lo que vale"}',
 '{"autosabotearse","postergar","no cobrar"}',
 '{"¿Qué escuchabas sobre el dinero cuando eras niña?","¿Qué sientes justo cuando te va bien?","¿Cobras lo que consideras justo? Si no, ¿qué te lo impide?"}',
 '{"Poner precio a algo sin descontarlo","Registrar una semana de ingresos y gastos sin juicio"}',
 '{"merecimiento"}',
 'Abundancia — E-MOTION', null, 'complementario')

on conflict (slug) do nothing;
